### ISSUE TITLE
lnvalid Feed lnput Name:xx

### ISSUE THREAD

**Issue by misss520** [NaruseMioShirakana/MoeSS#25]
I want to know what causes this error
![捕获](https://user-images.githubusercontent.com/80108847/225720181-066df3fe-1159-45c6-a90d-ba8b15b9ff44.PNG)

**Comment by NaruseMioShirakana** [comment]
Since there are pre-processing and post-processing differences between the models, and I don't want to overcomplicate the configuration files, I use the InputNames of the Onnx models to distinguish the models. Be sure to follow the export instructions in the ReadMe when exporting the Onnx models.
This problem may be caused by not specifying V3/V4 in the model configuration file. If you are using SoVits3.0, add    "SoVits3": true    to the model configuration file. If you are using SoVits4.0, add    "SoVits4": true    to the model configuration file, If you are using SoVits2, you do not need to fill in the first two items

**Comment by NaruseMioShirakana** [comment]
This problem may be caused by not specifying V3/V4 in the model configuration file. If you are using SoVits3.0, add "SoVits3": true to the model configuration file. If you are using SoVits4.0, add "SoVits4": true to the model configuration file, If you are using SoVits2, you do not need to fill in the first two items

**Comment by misss520** [comment]
I have done all the preparatory work, but when I use Moess for inference, I only get a bunch of noises. The inferred audio can hear the timbre, and the duration is the same, but there is no articulation, similar to a child's mouth. In Webui, my model can be inferred normally, I wonder what else is wrong, I am using SoVits4.0

**Comment by NaruseMioShirakana** [comment]
If you only got noises, please check your Hubert version.
SoVits4.0 has a dedicated Hubert model named "Hubert4.0", you can find it at [HuggingFace](https://huggingface.co/NaruseMioShirakana/MoeSS-SUBModel)
Place it in the hubert folder, and then change "hubert" to "hubert4.0" in the configuration file.

**Comment by NaruseMioShirakana** [comment]
If there is still noise, you can try to modifying the "DP噪声规模", Increase its value appropriately

**Comment by misss520** [comment]
Thank you, you are a very patient developer, all my problems were solved
